#!/bin/bash

# A lazy script to search for files belonging to a certain group in a lustre project dir

if [ $# -ne 2 ]; then
  echo "Lazy projects search"
  echo "Usage: $0 <project> <group>"
  exit 0
fi

echo "Searching project $1"
lfs find /projects/$1 ! -group $1 -print > ~/lu4/$1-$2.txt
export numfiles=`wc -l ~/lu4/$1-$2.txt`
echo "search found: $numfiles on projects"
