#!/bin/bash

# A lazy script to search for files belonging to a certain group in a lustre scratch dir

if [ $# -ne 2 ]; then
  echo "Lazy scratch search"
  echo "Usage: $0 <project> <outdir>"
  exit 0
fi

echo "Searching project $1"
lfs find /scratch/$1 ! -group $1 -print >> $2/$1s-scr.txt
export numfiles=`wc -l $2/$1s-scr.txt`
echo "search found: $numfiles on scratch"
